mongodb/docs-worker-pool

makefiles/Makefile.cloud-docs, makefiles/Makefile.docs, makefiles/Makefile.docs-bi-connector, makefiles/Makefile.docs-charts, makefiles/Makefile.docs-compass, makefiles/Makefile.docs-ecosystem, makefiles/Makefile.docs-k8s-operator, makefiles/Makefile.docs-spark-connector, makefiles/Makefile.docs-tutorials
docs Makefile with next gen target
=> creating makefile dir

worker/tests/mongo/globalConfig.json, worker/tests/unit/utils.test.js, worker/utils/utils.js
https://jira.mongodb.org/browse/DOCSP-7344
=> Encryption/Decryption Utility Functions

makefiles/Makefile.docs-node
=> fix node makefile

CHANGELOG.md, Dockerfile, Dockerfile.xlarge, README.md
Changes to the Dockerfile to accommodate tagging in parser and front-end.
* test locally
Also, added REAdME and CHANGELOG information for coming v0.2.0 release.
=> Bind to parser and front end versions

makefiles/Makefile.docs
Some fixes for the docs makefile:
1. change patch_id to patch for snooty parser params
2. adding a second c++ curl and swift curls for drivers examples
=> add c++ and swift, change patch

CHANGELOG.md
Addition of changelog for 0.4.3.
=> v0.4.3 CHANGELOG

makefiles/Makefile.docs-realm
This is a proposed fix for https://jira.mongodb.org/browse/DOP-1328 Mut won't publish for docs-realm.
I ran this in dry run mode from within the workerpool environment and got this output:
This was the first time I got actual files in the url output.
INFO:mut.stage:stage: initial staging setup: 0.00010932699660770595s
INFO:mut.stage:namespace: realm
INFO:mut.stage:stage: S3 filter created: 0.0002765520039247349s
INFO:mut.stage:Publishing _static, users, tutorial, deploy, dotnet, functions, searchindex.js, mongodb, authentication, admin, ios, procedures, sync, _images, hosting, .buildinfo, search, index.html, billing, objects.inv, reference, react-native, node, release.txt, graphql, realm-master.tar.gz, web, android, .htaccess, services, realm.tar.gz, values-and-secrets, triggers, …
=> fix to missing docs-realm published files issue

CHANGELOG.md
For Upgrade Ubuntu on Dockerfile (https://jira.mongodb.org/browse/DOP-1283)
[[legacy staged]](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/v4.0-0599bba/index.html) [[next gen staged]](https://docs-mongodbcom-staging.corp.mongodb.com/ea14b9a34/6fd074f/docs/docsworker-xlarge/v4.0/)
- changed Ubuntu to 20.4
- changed pip install calls
=> v0.4.4 candidate

StitchApp/WorkerpoolStaging/services/testDocsNodeDeployWebhook/source.js
[Relevant ticket](https://jira.mongodb.org/browse/DOP-1238)
[Spec](https://docs.google.com/document/d/1CvHbhA1lQEx4aEg109UVgkw2h_vCvC7wwve2mXEtRvU/edit?usp=sharing)
=> Stitch Side Testing Framework for DOP-1238

makefiles/Makefile.docs-realm
For https://github.com/mongodb/docs-worker-pool/pull/290
=> adding redirects prefix

makefiles/Makefile.docs, makefiles/Makefile.docs-mongocli
I have not been able to test this because I can't successfully build docs on non-xlarge
=> Fix for docs makefile

makefiles/Makefile.docs-bi-connector
For https://jira.mongodb.org/browse/DOP-1554
We want to pull in publishedbranches.yaml for staging builds so we can build the dropdown.
=> adding publishedbranches.yaml pull

makefiles/Makefile.docs-mongocli
Per https://jira.mongodb.org/browse/DOP-1542
* fixed up makefile
* checked publishedbranches.yaml
=> mongocli configs

publishedbranches/docs-compass.yaml
Fix incorrect display name on compass docs.
=> Update docs-compass published-branches.yaml

makefiles/Makefile.docs-compass
add publishedbranches.yaml pull to compass build
=> fix makefile depend

worker/jobTypes/S3Publish.js, worker/jobTypes/githubJob.js
re-add publish command for legacy builds
regression made via work related to https://jira.mongodb.org/browse/DOP-1238
=> Fix regression

worker/jobTypes/S3Publish.js, worker/jobTypes/productionDeployJob.js
=> fix spelling errors

publishedbranches/docs-mongocli.yaml
[JIRA](https://jira.mongodb.org/browse/DOCSP-13395)
=> (DOCSP-13395): Version bump to v1.9

makefiles/Makefile.docs-commandline-tools
Reverts mongodb/docs-worker-pool#369
=> Revert "point docs-commandline-tools at new bucket for deploy"

publishedbranches/docs-mongocli.yaml
Updated the MongoCLI version selector.
=> (DOCSP-14425) Version bump for mcli 1.12

publishedbranches/docs-kafka-connector.yaml
JIRA:
https://jira.mongodb.org/browse/DOCSP-14704
=> DOCSP-14704: kafka version update

publishedbranches/docs-node.yaml
It's finally happened, there's a new version of the node driver coming out.
=> begin branch versioning for docs-node

publishedbranches/docs-mongocli.yaml
Following this wiki: https://wiki.corp.mongodb.com/pages/viewpage.action?pageId=124687567
=> MongoCLI version bump 1.15

Dockerfile
Bumps our versions for release of latest parser/frontend.
=> 5-6-21 Release version bump

.github/workflows/deploy-integration-ec2.yml, .github/workflows/deploy-production-ec2.yml, Dockerfile, worker/jobTypes/githubJob.js
Changeset for various edits to github actions, and bumping parser versions.
=> Update master from integration

makefiles/Makefile.cloud-docs, makefiles/Makefile.cloud-docs-osb, makefiles/Makefile.devhub, makefiles/Makefile.devhub-content, makefiles/Makefile.docs, makefiles/Makefile.docs-404, makefiles/Makefile.docs-bi-connector, makefiles/Makefile.docs-charts, makefiles/Makefile.docs-commandline-tools, makefiles/Makefile.docs-compass, makefiles/Makefile.docs-datalake, makefiles/Makefile.docs-ecosystem, makefiles/Makefile.docs-golang, makefiles/Makefile.docs-java, makefiles/Makefile.docs-k8s-operator, makefiles/Makefile.docs-kafka-connector, makefiles/Makefile.docs-landing, makefiles/Makefile.docs-mongocli, makefiles/Makefile.docs-mongodb-shell, makefiles/Makefile.docs-mongodb-vscode, makefiles/Makefile.docs-node, makefiles/Makefile.docs-php-library, makefiles/Makefile.docs-realm, makefiles/Makefile.docs-spark-connector, makefiles/Makefile.docs-tutorials, makefiles/Makefile.govcloud-docs, makefiles/Makefile.mms-docs, makefiles/shared.mk
https://docs.google.com/document/d/1IxnFhyTcDVRLBECH6EXQIrc9ksFHTYrFe3biO2ELAQY/edit#
=> move next-gen-deploy to shared makefiles

publishedbranches/docs-mongocli.yaml
Version bump for MongoCLI v1.17
=> DOCSP-17129 - Version bump for MongoCLI v1.17

makefiles/Makefile.devhub-content
- Use new prod bucket
- Fix cp issue
=> Fixup new prod bucket, attempt to fix cp

publishedbranches/docs-node.yaml
=> bump node versions for .live

publishedbranches/docs-node.yaml
Add Node Version 4.1 to Node Docs.
=> DOCSP-17867 Update to Node Driver Version 4.1

worker/jobTypes/GatsbyAdapter.js
New feature flag for the Realm SDK Versioning work. Includes theoretically minor linting.
=> New feature flag: GATSBY_FEATURE_FLAG_SDK_VERSION_DROPDOWN

worker/jobTypes/GatsbyAdapter.js
Adds a falsey/nullish check and checks for env == 'false' to the env variable instantiation process.
Build the docker image, verify that env variables are not present inside the container after running from the image.
=> DOP-2413: Add nullish and falsey checks to env instantiation

publishedbranches/docs-node.yaml
=> DOCSP-17240

makefiles/shared.mk
Hopefully fixes all of our indentation problems
=> Fix indent for shared.mk

infrastructure/ecs-main/ecs_service.yml, infrastructure/ecs-main/serverless.yml
Adds an environment variable definition for the consistent nav feature flag, so that it can pull values from parameter store.
=> DOP-2420: Add feature flag to serverless.yml and ecs_service.yml

publishedbranches/docs-mongocli.yaml
- [JIRA](https://jira.mongodb.org/browse/DOCSP-18741)
=> DOCSP-18741 updates for new version

infrastructure/ecs-main/serverless.yml
Parallelize all the things for our nav launches!
=> Increase number of staging + production instances

publishedbranches/docs-java.yaml
Adding 4.4. Atlas has been updated
=> add version

config/default.json, src/services/commandExecutor.ts, tests/jobManager.integration.test.ts, tests/unit/job/productionJobHandler.test.ts, tests/unit/services/gitHubCommandExecutor.test.ts, tests/unit/services/jobSpecificCommandExecutor.test.ts, tests/utils/jobHandlerTestHelper.ts
Reverts changes related to max buffer size and usage of `cp.execSync`.
=> Dop 2625 giza stderr hotfix

publishedbranches/docs-visual-studio-extension.yaml
PR includes the following updates:
- Rename "main" branch to "master"
- Add "v1.0" as stable version
=> Update MongoDB Analyzer Docs Versions

publishedbranches/docs-node.yaml
https://jira.mongodb.org/browse/DOCSP-20256
=> DOCSP-20256: Node v4.3 version selector update

makefiles/Makefile.docs, makefiles/Makefile.docs-mongodb-internal
This PR updates the Node example locations for both the 10gen/docs-mongodb-internal and mongodb/docs repos.
=> Update Node example URLs with new location

publishedbranches/docs-java.yaml
https://jira.mongodb.org/browse/DOCSP-20835
=> DOCSP-20835: update Java driver version selector for 4.5

publishedbranches/docs-kafka-connector.yaml
Set up v1.7 branch MongoDB Kafka Connector.
https://jira.mongodb.org/browse/DOCSP-20932
=> (DOCSP-20932) Add v1.7 to Kafka Connector

publishedbranches/docs-node.yaml
=> add node 4.4

config/custom-environment-variables.json, infrastructure/ecs-main/ecs_service.yml, infrastructure/ecs-main/serverless.yml, src/job/jobHandler.ts
Parameter store values have been added for dotcomstg and dotcomprd instances.
=> DOP-2782: Add GATSBY_BASE_URL to frontend, from parameter store

src/repositories/repoBranchesRepository.ts
Removes an import that is causing regression tests to fail
=> bug-fix: remove line flagged by github actions

api/controllers/v1/slack.ts
Testing in staging after deploy, please hold off on testing until deploy finishes 🤞
=> Add helper to ensure parallel jobs have prefix at correct granularity

makefiles/Makefile.docs, makefiles/Makefile.docs-mongodb-internal
Addendum for #640 . Gonna go ahead and merge this immediately but wanted to make this a PR for visibility.
=> Fix 404 VersionedApiExamples.cs file name

infrastructure/ecs-main/serverless.yml
=> increase prod ecs cpu and memory

infrastructure/ecs-main/ecs_service.yml, src/job/manifestJobHandler.ts, src/onDemandApp.ts
- https://github.com/mongodb/docs-worker-pool/pull/653
=> bugfix iam policy for reading params from ecs

api/controllers/v1/slack.ts
Reverts mongodb/docs-worker-pool#681
=> Revert "DOP-2866: fix semi-versioned repo logic harder"

makefiles/Makefile.docs, makefiles/Makefile.docs-atlas-cli, makefiles/Makefile.docs-bi-connector, makefiles/Makefile.docs-compass, makefiles/Makefile.docs-datalake, makefiles/Makefile.docs-landing, makefiles/Makefile.docs-mongocli, makefiles/Makefile.docs-mongodb-internal, makefiles/Makefile.docs-php-library, makefiles/Makefile.docs-stage
This reverts commit 15cff654d4e3ddb0a0ec32122eced824fcf19fb9.
Do not merge until the shared.mk changes are released
=> DOP-2965: Switch all makefiles to using bundles

api/controllers/v1/slack.ts
=> sort the entitled branches list in the slack modal

.eslintrc.js, .github/workflows/test-oas-page-builder.yml, modules/oas-page-builder/.eslintrc.js, modules/oas-page-builder/index.ts, modules/oas-page-builder/package-lock.json, modules/oas-page-builder/package.json, modules/oas-page-builder/tests/unit/services/pageBuilder.test.ts, modules/oas-page-builder/tests/unit/services/redocExecutor.test.ts
[DOP-3431](https://jira.mongodb.org/browse/DOP-3431)
* Adds dependencies for linting and formatting OAS module
* Fixes pre-existing lint issues for the module
=> DOP-3431: Add GH workflow for testing OAS Page Builder module

.github/workflows/test-oas-page-builder.yml, .github/workflows/test-persistence.yml, .github/workflows/test.yml
cc @rayangler the master branch is failing at CI steps due to no checkout being invoked.
we'll need to merge and test this since merge and PR actions are separate
=> DOP-3439: use checkout for merge changes

modules/persistence/src/services/metadata/ToC/index.ts, modules/persistence/src/services/metadata/associated_products/index.ts, modules/persistence/tests/metadata/associated_products.test.ts
example of error here: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=63d3176038206a77a232deb0
steps to reproduce error locally on master branch.
```
cd modules/persistence
npm install
npm build
npm run start -- --path <path/to/bundle.zip>
```
was able to successfully upload on branch to snooty_dev: (query snoot_dev for _id with Object id 63d42903ea79794c067ac387)
=> DOP-3479: update input for prefixFromEnvironment

modules/persistence/src/services/metadata/index.ts
when merging, forgot to update these lines. PTAL
https://github.com/mongodb/docs-worker-pool/pull/740/files#diff-4ae52e6a65d78db41a48a0bbc021216e5cbadeb929afb5eb6015e81d37f4f4c9R39-R42
=> minor fix. merge conflict updated

api/controllers/v1/jobs.ts
Ticket
[DOP-3586](https://jira.mongodb.org/browse/DOP-3586)
=> [DOP-3586]: Cancel archive job for staging

.github/workflows/deploy-prd-ecs.yml, .github/workflows/deploy-stg-ecs.yml, infrastructure/ecs-main/buckets.yml, infrastructure/ecs-main/serverless.yml, infrastructure/ecs-repo/serverless.yml, serverless.yml
This just creates the environments: it does not wire anything up.
If this looks good, I can push it into testing!
=> DOP-3593: Add legacy queue infrastructure

src/job/jobManager.ts
Adds an exclusion array to fix an issue where `mms-docs` was incompatible with deployment benchmark changes
=> Add exclusion array to jobManager.ts

.github/workflows/deploy-stg-ecs.yml, api/handlers/jobs.ts, src/job/jobHandler.ts, src/repositories/jobRepository.ts, tests/unit/job/api/jobs.test.ts, tests/unit/job/productionJobHandler.test.ts, tests/unit/repositories/jobRepository.test.ts
DOP-3904
Updates `Job` with designated `status` on SnootyBuildWebhook completion.
=> DOP-3904: SnootyBuildWebhook updates Job status

cdk-infra/lib/constructs/worker/worker-env-construct.ts, src/job/jobHandler.ts
Adds a feature flag needed for the persistence module to update page ASTs
=> Add missing feature flag for persistence module

.github/scripts/webhook-pr-comment.js, .github/workflows/deploy-feature-branch.yml
Added functionality for the initial deploy of the feature branch infrastructure to comment on the PR with the webhook URL.
The last build error can be ignored. I cancelled the feature branch cleanup workflow, so it marks the commit as a failure.
=> [FEATURE]: Comment on PRs with webhook URL for feature branch

infrastructure/ecs-main/buckets.yml
FWIW, I've already YOLO done this in the AWS console 😁 😬
=> DOP-2345: Add redirect rule for php library from master -> current

.github/workflows/README.md, .github/workflows/clean-feature-branch.yml, .github/workflows/deploy-feature-branch.yml, .github/workflows/deploy-stg-ecs.yml, .github/workflows/deploy-stg-enhanced-webhooks.yml, .github/workflows/deploy-stg-enhanced-worker.yml, .github/workflows/test-oas-page-builder.yml, .github/workflows/test-persistence.yml, .github/workflows/test.yml, .github/workflows/update-feature-branch.yml, README.md, src/job/manifestJobHandler.ts
Clarity on how to test this welcome!
=> DOP-3949: Rename 'master' to 'main'

.github/workflows/deploy-feature-branch.yml, .github/workflows/update-feature-branch.yml, cdk-infra/lib/constructs/worker/worker-env-construct.ts, cdk-infra/utils/env.ts, src/job/jobHandler.ts
This PR resolves the hanging build issue for feature branch staging builds. To resolve this, the call to the Gatsby Cloud webhook has been removed for feature branches.
=> Hanging build hotfix

makefiles/Makefile.docs-cpp
Makefile for new repo
https://github.com/mongodb/docs-cpp
=> DOP-4345 add docs-cpp makefile

.github/pull_request_template.md
Creates PR template with checks
=> DOP-4289 readme

makefiles/Makefile.docs-scala
DOP-4346
New Makefile for new docs-scala repo
=> DOP-4346: new docs-scala Makefile

makefiles/Makefile.docs-c
=> DOP-4344: Add Makefile for C repo

makefiles/Makefile.docs-java-rs
DOP-4350
Adding makefile for the Java RS Driver.
- - [X] This PR does not introduce changes that should be reflected in the README
=> DOP-4350: Adding Java RS Makefile

.github/workflows/deploy-prd-enhanced-worker.yml, .github/workflows/deploy-stg-enhanced-worker.yml
DOP-NNNN
- - [ ] This PR does not introduce changes that should be reflected in the README
=> [HOTFIX]: add npm ci

.github/workflows/clean-feature-branch.yml
[DOP-4578](https://jira.mongodb.org/browse/DOP-4578)
[verification that the clean up process works again](https://github.com/mongodb/docs-worker-pool/actions/runs/8971895874)
- - [ ] This PR does not introduce changes that should be reflected in the README
=> Cleanup Feature Branch Infrastructure Failure

api/controllers/v1/slack.ts, api/handlers/slack.ts
[DOP-4549](https://jira.mongodb.org/browse/DOP-4549)
This PR implements additional error checking, after it was discovered that the recently merged PR will cause the slack modal not to appear if a user has a bad entitlement.
=> DOP-4549 (hotfix)

.github/workflows/deploy-prd-ecs.yml, .github/workflows/deploy-stg-ecs.yml, README.md
DOP-NNNN
- - [ ] This PR does not introduce changes that should be reflected in the README
=> Pin Serverless to a specific version

makefiles/Makefile.docs-django
=> DOP-5279: Add new docs-django Makefile
