- makefiles/Makefile.docs-node
https://jira.mongodb.org/browse/DOCSP-8878
This PR adds the node production bucket to the makefile and adds targets to build and deploy to production with next gen (woo hoo!).
At this point, it's probably suboptimal to test this manually. So the CR here should probably consist of looking at the targets (make-next-gen-html and deploy-next-gen) to make sure they look like they could potentially work.
Since this prod bucket is new and not attached to any sort of CDN service or DNS record at the moment, we can test this with the staging autobuilder without impact to our existing docs site.
> add makefile for node

- makefiles/Makefile.devhub-content
This PR changes the branch of the snooty frontend code used to render the developer.mongodb.com from stage to master.
To test:
1. Fork the https://github.com/mongodb/devhub-content repository
2. Make sure you have added the github webhook for the autobuilder to your fork
3. checkout a new branch, make a change, commit and push your change
4. If you have properly configured your autobuilder hook, you should get a link with your new staged content with changes via slack.
> devhub content

- Dockerfile.xlarge
This PR installs the devhub frontend codebase at image build time so that we can save time on the install.
It is related to: https://jira.mongodb.org/browse/DOP-999
The change is made in one Dockerfile in order to test in stage, if it works, I'll make a PR on the plain dockerfile.
> Dop 999docker

- makefiles/Makefile.docs-datalake
- makefiles/Makefile.docs-mongodb-shell
- makefiles/Makefile.docs-mongodb-vscode
Reverting commit based builds for datalake, shell and vscode docs because the writers prefer to have latest commit builds instead of commit-specific.
> testing makefile changes for branch builds

- worker/jobTypes/githubJob.js
- worker/tests/unit/githubPushJob.unit.test.js
**Overview:**
The goal of DOP-64 was to catch and log parser failures. However, the initial fix relied on checking the error's code. On the parser side, it throws an error code 1 for parser failures and error code 2 for all other diagnostic errors. 
However, make propagates all errors as error code 2. This meant on the server side we couldn't differentiate error codes without parsing stderr, which is a brittle and weak solution. 
I was eventually able to write the conditional I needed in the next-gen-html target ([demonstrated in this PR](https://github.com/mongodb/docs-worker-pool/pull/197), which you will need to test _this_ PR). In this way, we can differentiate error codes from within the makefile. 
note to andrew: the initial condition we tried `if [$? -eq 1]; then exit 1; else exit …
> DOP-64 FIX

- makefiles/Makefile.docs
- makefiles/Makefile.docs-stage
These makefile changes enable patch id to be incorporated into builds of branches that have uncommitted/unpushed patches applied.
It enables the use of the commitless staging script with the server docs repository.
This makefile was tested using docs-stage.
> new docs makefile

- makefiles/Makefile.docs-bi-connector
This makefile logic allows us to throw an error ONLY when parser throws error code 1 in the course of running `snooty build...`. 
We exit 0 on all other errors.
> Update Makefile.docs-bi-connector for catching parser failure

- makefiles/Makefile.docs-datalake
Adding commitless staging to docs-datalake. docs-datalake only uses the commit hash during commitless staging builds, and otherwise is built using just the branch.
Ticket:
https://jira.mongodb.org/browse/DOP-1305
> adding commitless staging docs-datalake DOP-1305

- worker/jobTypes/S3Publish.js
- worker/jobTypes/productionDeployJob.js
https://jira.mongodb.org/browse/DOP-1238 introduced a regression for legacy builds -- that we didn't catch because we never tested legacy deploys in any of our testing. 
this [job](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?jobId=5f46aa172e8d3a887d55db55) successfully updated docs-realm:
- the realm PR: https://github.com/mongodb/docs-realm/pull/582 and (one of the) corresponding changed page https://docs.mongodb.com/realm/dotnet/
I am going to squash all the commits into one when we merge (I squashed locally but then when I tried to push the changes, it complained I didn't have updates from the remote...bc ya know, I squashed after having already pushed. Mondays!)
> add publish command for legacy builds

- makefiles/Makefile.docs-realm
We're going to need to apply something similar to many other makefiles I believe, but we *need* to change how the prefix is passed in for this to not be really weird
> Fix realm search index URL

- Dockerfile
- Dockerfile.nonxlarge
make the xlarge version the default dockerfile we use - also remove the latestTag var, forcing us to specify the tags we want to use (otherwise building docker will crash).
> make dockerfile xlarge the default dockerfile

- makefiles/Makefile.cloud-docs-osb
Attempts to deploy cloud-docs-osb fail on the following:
```
{
time: "Thursday, January 21, 2021, 14:34:38 UTC",
reason: "Error: Command failed: . /venv/bin/activate && cd repos/cloud-docs-osb && rm -f makefile && make get-build-dependencies && make next-gen-html
make: *** No rule to make target 'get-build-dependencies'.  Stop.
"
}
```
This should solve that issue.
> DOP-1913: add get-build-dependencies to cloud-docs-osb makefile

- makefiles/Makefile.docs-mongodb-vscode
Currently the wrong URL is passed to `mut-index`, so search results 404.
> Correct mut-index invocation in vscode makefile

- makefiles/Makefile.cloud-docs
- makefiles/Makefile.cloud-docs-osb
- makefiles/Makefile.cloud-docs-stage
- makefiles/Makefile.devhub
- makefiles/Makefile.devhub-content
- makefiles/Makefile.devhub-content-integration
- makefiles/Makefile.docs
- makefiles/Makefile.docs-bi-connector
- makefiles/Makefile.docs-charts
- makefiles/Makefile.docs-commandline-tools
- makefiles/Makefile.docs-compass
- makefiles/Makefile.docs-datalake
- makefiles/Makefile.docs-ecosystem
- makefiles/Makefile.docs-java
- makefiles/Makefile.docs-k8s-operator
- makefiles/Makefile.docs-kafka-connector
- makefiles/Makefile.docs-landing
- makefiles/Makefile.docs-mongocli
- makefiles/Makefile.docs-mongodb-shell
- makefiles/Makefile.docs-mongodb-vscode
- makefiles/Makefile.docs-node
- makefiles/Makefile.docs-realm
- makefiles/Makefile.docs-spark-connector
- makefiles/Makefile.docs-stage
- makefiles/Makefile.docs-tutorials
- makefiles/Makefile.govcloud-docs
- makefiles/Makefile.mms-docs
- makefiles/shared.mk
This PR contains the necessary makefile side changes to fix bugs associated with generating the search index manifest filename on the autobuilder. 
I also used this as an opportunity to start the work of the shared makefile, as this solution required adding an identical target to all of our makefiles (get-project-name). 
This sheet contains all the functional tests I did to verify the new work:
https://docs.google.com/spreadsheets/d/1R1Jqx1OOZX37JzTppouNMxwckJCpXtOAQXGScM09bwI/edit?usp=sharing
PR for the node side changes to come ASAP
> Makefile side changes for DOP-1915, DOP-1858, DOP-1812 + Beginning shared makefile

- makefiles/Makefile.docs-landing
Duplicate makefile update as introduced in https://github.com/mongodb/docs-landing/pull/64.
> DOP-1946: Write sitemap index to root

- makefiles/Makefile.docs-golang
- publishedbranches/docs-golang.yaml
[[DOP-2025](https://jira.mongodb.org/browse/DOP-2025)]
- Do not include commit hashes in staging jobs
- The [mongodb/docs-golang](https://github.com/mongodb/docs-golang) repo will be using `main` as its primary branch name instead of `master`; I tried to reflect that here but not sure if there is anywhere else where that would have an impact
- It looks like every repo has its own integration bucket, so perhaps we need to make one?
> DOP-2025: Add Go docs build pipeline

- Dockerfile
Per this lovely debugging message:
```
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/pip/2.7/get-pip.py
Sorry if this change causes any inconvenience for you!
We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor
version.
There are no more renames/URL changes planned, and we don't expect that a need
would arise to do this again in the near future.
Thanks for understanding!
- Pradyun, on behalf of the volunteers who …
```
> Updates the URL whence we download pip2

- publishedbranches/docs-node.yaml
Renaming stable to current to follow other driver patterns. We will update aliases once this is merged.
> renames stable to current

- worker/tests/unit/mongo.test.js
- worker/utils/environment.js
- worker/utils/mongo.js
- worker/worker.js
In the current iteration of the docs-worker-pool, every instance of the autobuilder is spun up to listen to updates to the same, single collection. This is great for production - we have four autobuilder instances listening to the same collection, thus building sites faster and more robustly. However, it represents a huge bottleneck for staging. 
If multiple staging instances of the autobuilder are up, each instance will pick up a job whenever it becomes available despite the fact that a job may have been intended to run on a different staging instance that has different tests implemented.  This is why I've always had to ask when the team wanted to test on integration - because I needed my tests jobs to be run through my staging instance (especially if I was testing publish/deploys!). …
> DOP-2043 allow multiple autobuilder staging instances

- makefiles/Makefile.devhub-content
- makefiles/Makefile.devhub-content-integration
This PR attempts (keyword!) to use the `STRAPI_PUBLICATION_STATE` variable defined in [this branch](https://github.com/mongodb/docs-worker-pool/compare/master...madelinezec:DOP-2144?expand=1) and pipe it to the `env.production` file. I also opted to wrap in a conditional to only add the field should it exist.
This _should_ do the trick?
> DEVHUB-636: Consume STRAPI_PUBLICATION_STATE

- publishedbranches/docs.yaml
We've bumped the versions in our GitHub repo so now v5.0 content lives on branch `master` and v4.4 content lives on branch `v4.4`.
> fix manual published branches for 5.0 version bump

- makefiles/Makefile.docs
Seems like we weren't calling `mut-redirects` when we should be.
> Add missing mut-redirects to Makefile.docs

- makefiles/Makefile.docs
JIRA: https://jira.mongodb.org/browse/DOP-2307
These changes add curl calls for Versioned API test files for CSharp and Node.
> DOP-2307 adds Versioned API test calls to DOCS Makefile

- publishedbranches/docs.yaml
NOTE: I'm not entirely sure I did this correctly because I'm a little foggy on the meanings of `stable`, `upcoming`, and `git.branches.manual`. I feel like in next-gen these don't do anything but might be misremembering.
> (DOCSP-17512): Remove 'upcoming' from manual version flipper for 5.0

- makefiles/Makefile.docs-php-library
- publishedbranches/docs-php-library.yaml
Requisite updates to make phplib buildable on snooty so we can assess how much work it's going to be to migrate.
> DOP-2311: add phplib published branches so we can stage with snooty

- makefiles/Makefile.docs
- makefiles/shared.mk
Ugh.
Relevant context: for reasons that are hard to deduce, we upload the Manual's search index manifest as docs-<something> rather than manual-<Something>. Because of the way the front-end works, that means we have "Docs" as a "Product" and "Manual" as a product, which is obviously silly. This will (very hackily) fix that situation while we sort out a more permanent solution as part of the Version Management project.
> DOP-2343: (TEMP HACK) fix manifest prefix for manual to align with legacy

- worker/jobTypes/GatsbyAdapter.js
Adds a feature flag at GATSBY_FEATURE_FLAG_CONSISTENT_NAVIGATION to the autobuilder.
This is intended to initialize an env var defined in each instance where appropriate within our `rundocker.sh`.
> Added GATSBY_FEATURE_FLAG_CONSISTENT_NAVIGATION to GatsbyAdapter

- publishedbranches/docs.yaml
The goal of this PR is to create a new published branch of the manual for 5.1 content. The version dropdown should read `v5.1 (upcoming)`, and the corresponding GitHub branch for v5.1 content is `master`.
> (DOCSP-18215): Update manual published branches for 5.1 upcoming

- publishedbranches/docs.yaml
Since the 5.1 version dropdown entry is non-numeric, we need to explicitly specify "Version" for "Version" to appear in the dropdown copy.
> Add 'Version' string to manual 5.1 dropdown entry

- makefiles/Makefile.devhub-content
- makefiles/Makefile.devhub-content-integration
[JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-505)
Howdy! Me again
We have completed our subdomain swap so it is time for us to undo the changes made to support pushing to two sites at once. Specifically, this PR:
- Removes the redundant build/stage/publish. This now should just use the new logic.
- Removes use of gatsby-config.prod and gatsby-config.prod-new so on the front-end we can consolidate to one config file by leveraging the PATH_PREFIX environment variable. [Related PR can go in after this change](https://github.com/mongodb/devhub/pull/951)
Any feedback appreciated, thanks!
> DEVHUB-505: Consolidate and cleanup DevHub jobs

- makefiles/Makefile.docs-mongocli
The `get-build-dependencies` target is only run in deploy builds, it seems,
so we have to do this to add the git submodule invocation.
> DOP-2415: Take 2 at fetching git submodules

- makefiles/Makefile.devhub-content
Fixes the `cp` commands to not use trailing slashes as they used to before we made any changes
> DEVHUB-505 Pt 2: Fixed Commands

- makefiles/shared.mk
Adds indent to echo in `shared.mk`. Hopefully fixes the missing separator issue
> Add indent to echo

- makefiles/Makefile.docs-golang
- publishedbranches/docs-golang.yaml
This is sort of a hacky way to get `docs-golang` to publish to both `drivers/go/master` while its alias publishes to `drivers/go/current` without actually having two active branches/versions.
We definitely need to make the appropriate adjustments when prepping the repo for another branch.
> Update golang prefixes

- publishedbranches/docs-charts.yaml
[DOCSP ticket requesting Charts 19.12 be removed from dropdown](https://jira.mongodb.org/browse/DOCSP-18822)
> Remove Charts 19.12 from version and git fields

- makefiles/Makefile.devhub-content
As a result of using `PATH_PREFIX` in next-gen-html for all jobs, we should update the s3 bucket push to be /developer and update in place
> DEVHUB-505: Use Universal PATH_PREFIX for staging

- config/default.json
- src/services/commandExecutor.ts
- tests/jobManager.integration.test.ts
- tests/unit/services/gitHubCommandExecutor.test.ts
- tests/unit/services/jobSpecificCommandExecutor.test.ts
Switches our usage of `promisify` and `child_process.exec` to `child_process.execSync`, with an increased buffer size of 16MB for verbose log ouptuts
https://nodejs.org/api/child_process.html#child_processexecsynccommand-options
Updates tests to reflect new usage
> DOP-2571: execSync with increased buffer

- src/services/commandExecutor.ts
- tests/unit/job/productionJobHandler.test.ts
- tests/utils/jobHandlerTestHelper.ts
Updates our error output to cast buffer to string, and updates relevant tests for the changed return signature.
> hotfix: Update output for changed error signature

- makefiles/Makefile.docs-visual-studio-extension
Add a make file [for this repository](https://github.com/mongodb/docs-visual-studio-extension).
Next-Gen configuration scripts [can be found in this branch of this fork](https://github.com/biniona-mongodb/docs-visual-studio-extension/tree/next-gen) of the preceding repository.
I don't understand the structure of this Makefile well, so I largely copied the most recent other Deved-DBX Makefile (the makefile for `docs-golang`). Let me know if anything here looks odd or off the mark.
> Add Visual Studio Makefile

- makefiles/Makefile.docs-visual-studio-extension
- publishedbranches/docs-visual-studio-extension.yaml
Update prefix of docs site. The reason for this change is that the product this site documents was renamed from "Visual Studio Extension" to "MongoDB Analyzer" as the docs set was being written.
This PR is depended on [by this PR](https://github.com/mongodb/docs-visual-studio-extension/pull/10).
> (DOCSP-20213) Update Prefix For docs-visual-studio-extension Repo

- .babelrc
During testing, we receive the warning:
```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
```
Babel’s loose mode transpiles ES6 code to ES5 code that is less faithful to ES6 semantics. We do not seem to need this feature, so I propose we …
> remove-loose-babel-option: as described

- .husky/pre-commit
- .husky:pre-commit
Changes `.husky:pre-commit` to `.husky/pre-commit`. Does not run the formatter in this PR
> Pre commit hook fix: change pathname

- publishedbranches/docs-mongocli.yaml
[JIRA](https://jira.mongodb.org/browse/DOCSP-20655)
> (DOCSP-20655): Updating the mcli version flipper for v1.22.0

- makefiles/Makefile.docs
- makefiles/Makefile.docs-mongodb-internal
Passes in `REPO_NAME` as env variable to frontend for `docs` and `docs-mongodb-internal` only. This is to differentiate the two repos when fetching their versions/branches on the frontend, while maintaining the same project names for both. This change *should* be backwards compatible and not cause any disruption in docs team workflow since the frontend currently doesn't do anything with this env variable.
If things look good here, I can commit the same changes directly to the `DOP-2747-meta` and `DOP-2747-meta-stg` branches.
> DOP-2780: Add REPO_NAME to docs and docs-mongodb-internal

- .github/workflows/deploy-stg-ecs.yml
- src/job/jobHandler.ts
- tests/data/data.ts
- tests/unit/job/productionJobHandler.test.ts
When the `pathPrefix` is an empty string, and `urlSlug` is `null` or falsy, the frontend should receive `/` as its `PATH_PREFIX` env variable.
[Atlas](https://docs-atlas-stg.s3.us-east-2.amazonaws.com/index.html)
[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/index.html)
[Manual](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/manual/) (should have no changes)
> DOP-2788: Set PATH_PREFIX env variable to '/' for deploys to bucket root

- src/job/jobHandler.ts
- src/job/jobValidator.ts
- src/job/productionJobHandler.ts
[DOP-2801](https://jira.mongodb.org/browse/DOP-2801). This attempts to solve this issue of incorrect generation of search manifests e.g. `realm-.json `
- Also adds a conditional to the job validator to check that the project string exists. 
- Also moves the function declaration around to be more local to where it is used, and removes Promise / async
Is this appropriate @GuruPKK?
> manifest-prefix-fix: Add conditional to manifestPrefix function

- makefiles/Makefile.docs-meta
```
make -n -f Makefile.docs-meta  stage
mut-publish build/add-meta/html docs-mongodb-org-dotcomstg --prefix=docs-meta --stage 
echo "Hosted at https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-meta/heli/add-meta/index.html"
```
> fix docs-meta

- api/controllers/v1/slack.ts
Inactive branches may, regrettably, still need to be deployed. Inactive branches that build on Snooty need to be deployed
via the Autobuilder. This continue causes attempts to deploy active: false branches to silently fail to push to the queue, which makes EOL-ing 'legacy' docs impossible.
(This replaces the PR from my fork, which can't github action due to its being a fork.)
> DOP-2866: removes continue when active != true

- makefiles/Makefile.docs-cluster-to-cluster-sync
- publishedbranches/docs-cluser-to-cluster-sync.yaml
Also adds a dodgy little publishedbranches since there's a build step that looks for it even though it's unnecessary.
> DOP-2711: add makefile & published branches for cluster-sync

- makefiles/Makefile.docs
- makefiles/Makefile.docs-mongodb-internal
This PR updates the Makefiles for `docs` and `docs-mongodb-internal` so that their drivers examples are up-to-date. The changes were copied from the [docs repo's Makefile](https://github.com/mongodb/docs/blob/f15df6e24dda9e36f7c7029e75921f3b01121b53/Makefile#L113)
> Update stale drivers examples for docs

- src/job/manifestJobHandler.ts
Uses repoBranches to source the basename url instead of the payload url (which is currently the source url for the content repo)
> DOP-N/A: Use repoBranches url instead of payload url

- .github/workflows/deploy-dev-ecs.yml
- .github/workflows/deploy-stg-ecs.yml
This PR updates the triggers for the dev and staging pipeline so that we don't deploy into staging via pull request.
We'll still have to revisit the pipeline, but this should make staging reflect the main branch.
If we need to deploy into staging of a feature branch, then the pipeline trigger can be manually updated for that branch.
> [DOP-2946] stabilize staging pipeline

- src/job/jobHandler.ts
Adds a boolean to check if the property being deployed is aliased, and whether it is the primary alias.
Only enqueues a manifest generation on primary alias jobs for aliased properties.
> DOP-N/A: Only enqueue a manifest for primaryAliases

- src/job/jobHandler.ts
- tests/unit/job/manifestJobHandler.test.ts
Ran a `test-deploy` and `atlas-master.json` exists!
> DOP-2978: Fix manifest prefix for cloud-docs

- api/controllers/v1/slack.ts
Why would you want to do this? You're Charts and you've only got 1 actual version, but also a legacy version that you want to build. You actual version should stay at www.mongodb.com/docs/charts/ not at www.mongod.com/docs/charts/master, while 19.12 should build to www.mongodb.com/docs/charts/19.12/.
> DOP-2866: permit building to '/' if urlSlug == null and publishOriginalBranchName == false

- .github/workflows/deploy-stg-ecs.yml
- src/job/productionJobHandler.ts
- src/services/cdn.ts
- tests/unit/job/productionJobHandler.test.ts
- tests/unit/services/K8SCDNConnector.test.ts
[DOP-2902](https://jira.mongodb.org/browse/DOP-2902)
This ticket allows for a single wildcard invalidation in the CloudFront CDN instead of multiple individual objects being invalidated, which is an expensive operation. 
Notes: 
Before merge, the temporary workaround for the staging pipeline and the threshold for URL wildcard purging (which is currently set to 1 for testing purposes, should be 250) will be changed. Extraneous console.log()s will also be removed, which were added for greater visibility in the logs.  
[Invalidation Status for Atlas](https://cdnvalidator.devops.staging.corp.mongodb.com/api/v1beta1/distributions/mongodbcom-staging-docs/invalidations/I2HFI80AX9C73S)
[Invalidation Status for Docs](https://cdnvalidator.devops.staging.corp.mongodb.com/api/v1beta1/distributions/mon …
> DOP-2902: Perform wildcard invalidations when invalidating more than 250 objects

- .github/workflows/build-docker-ecr.yaml
This PR changes the ghcr repo name we use for caching docker builds. In the first pass of the new pipeline link [link](https://github.com/mongodb/docs-worker-pool/pull/657) the cache name would be `{owner}/{repo}:{branch}-cache`. Now the name has inputs to control the format, and defaults to `{owner}/caches/{repo}:{branch}`.
> improve control for cache naming

- infrastructure/ecs-main/buckets.yml
- infrastructure/ecs-main/serverless.yml
[DOP-3054](https://jira.mongodb.org/browse/DOP-3054)
This PR redirects any URLs following the format of `docs/master/*` to `docs/upcoming/*`.
> DOP-3054: Add redirects for docs/master to docs/upcoming

- .github/workflows/test.yml
[DOP-2861](https://jira.mongodb.org/browse/DOP-2861)
Adds a basic CI infrastructure to all autobuilder PRs via GitHub Actions. The job currently runs eslint for linting, Prettier for formatting, and jest for unit testing.
**Note**:  11 of the 153 tests currently fail. We will address the failing tests in another ticket. For now, I've included the `continue-on-error` flag to ensure the overall run is treated as a success regardless of test failures. Once we've fixed the tests, we should remove the line from `test.yml`
Follow-up work is being tracked in [DOP-3080](https://jira.mongodb.org/browse/DOP-3080)
> DOP-2861: Add GitHub Workflow for CI (Linting, Formatting & Tests)

- makefiles/Makefile.docs-404
[DOP-3071](https://jira.mongodb.org/browse/DOP-3071?src=confmacro)
To add custom 404 pages back to our site post subdomain consolidation, we need to upload the built version of the `docs-404` content repo to each of the 7 buckets that hosts docs content (`docs-java-{env}`, `docs-mongodb-org-{env}`, etc). Since we only need to display a custom 404 page in production and pre-production environments, the Makefile only uploads the built files using `mut` if `SNOOTY_ENV` is equal to `dotcomprd` or `dotcomstg`.
After this PR has been merged, we will need to run a `/test-deploy` in Slack on `docs-404` to see if the files get uploaded successfully.
```
{
"repoName": "docs-404",
"branches": [
{
"publishOriginalBranchName": false,
"active": true,
"gitBranchName": "master",
"isStableBranch": false, …
```
> DOP-3071: Update docs-404 Makefile to upload built assets to multiple environment-specific S3 buckets

- infrastructure/ecs-main/buckets.yml
- https://github.com/mongodb/docs-worker-pool/pull/667
- https://github.com/mongodb/docs-worker-pool/pull/679
This PR removes the redundant prefix in the redirect rule we have on s3. For example the condition `docs-qa/docs/master` becomes just `docs-qa/master`.
> update master -> upcoming redirect

- infrastructure/ecs-main/buckets.yml
- infrastructure/ecs-main/serverless.yml
[DOP-3071](https://jira.mongodb.org/browse/DOP-3071)
A follow-up to #674. Successfully tested the Makefile in preprod `dotcomstg` environment. We now need to update our CloudFormation stack to ensure the 404 page is served in both `dotcomstg` and `dotcomprd` environments.
Goal is to only set the `ErrorDocument` property in `dotcomstg` and `dotcomprd`. Outside of those environments, we will continue to serve the default S3 error page.
> DOP-3071: Update CloudFormation template to specify custom S3 error document

- .github/workflows/test.yml
- api/config/custom-environment-variables.json
- api/config/default.json
- config/custom-environment-variables.json
- config/default.json
- config/test.json
- jest.config.js
- src/job/productionJobHandler.ts
- src/repositories/jobRepository.ts
- src/repositories/repoBranchesRepository.ts
- src/services/cdn.ts
- src/services/commandExecutor.ts
- tests/data/data.ts
- tests/jobManager.integration.test.ts
- tests/unit/job/manifestJobHandler.test.ts
- tests/unit/job/productionJobHandler.test.ts
- tests/unit/job/stagingJobHandler.test.ts
- tests/unit/jobManager.test.ts
- tests/unit/repositories/jobRepository.test.ts
- tests/unit/repositories/repoBranchesRepository.test.ts
- tests/unit/services/fastlyConnector.test.ts
- tests/unit/services/hybridJobLogger.test.ts
- tests/unit/services/jobSpecificCommandExecutor.test.ts
- tests/utils/jobHandlerTestHelper.ts
[DOP-3080](https://jira.mongodb.org/browse/DOP-3080)
[DOP-2861](https://jira.mongodb.org/browse/DOP-2861) added a basic CI workflow for the autobuilder via GitHub actions. However, CI remained useless because of pre-existing failing Jest tests. This PR fixes the 11 failing tests and removes the `continue-on-error` flag from our GitHub Actions workflow `yaml` file to ensure any code regressions are caught on future PRs.
We also had to disable coverage thresholds in `jest.config.js` to ensure Jest returns a good exit status on CI. Current coverage remains ~67%, while the thresholds were set to 90%.
See comments in the diff for details on each changes/removed test.
> DOP-3080: Resolve failing unit tests in autobuilder test suite

- .github/workflows/test.yml
- api/config/custom-environment-variables.json
- api/config/default.json
- api/controllers/v1/slack.ts
- config/custom-environment-variables.json
- config/default.json
- config/test.json
- jest.config.js
- src/job/productionJobHandler.ts
- src/repositories/jobRepository.ts
- src/repositories/repoBranchesRepository.ts
- src/services/cdn.ts
- src/services/commandExecutor.ts
- tests/data/data.ts
- tests/jobManager.integration.test.ts
- tests/unit/job/manifestJobHandler.test.ts
- tests/unit/job/productionJobHandler.test.ts
- tests/unit/job/stagingJobHandler.test.ts
- tests/unit/jobManager.test.ts
- tests/unit/repositories/jobRepository.test.ts
- tests/unit/repositories/repoBranchesRepository.test.ts
- tests/unit/services/fastlyConnector.test.ts
- tests/unit/services/hybridJobLogger.test.ts
- tests/unit/services/jobSpecificCommandExecutor.test.ts
- tests/utils/jobHandlerTestHelper.ts
Previously 'fixed' in https://github.com/mongodb/docs-worker-pool/pull/635 but actually this case hits earlier in the loop logic and then getting `continue`'d because the `master` branch doesn't have any aliases.
> DOP-2866: fix semi-versioned repo logic harder

- makefiles/Makefile.docs-bi-connector
Switch to using snooty manifests rather than Atlas for document exchange on bi-connector.
```
make -f ~/work/docs-worker-pool/makefiles/Makefile.docs-bi-connector next-gen-html
```
performs a complete build
> DOP-2965: Use snooty manifests for bi-connector

- makefiles/Makefile.docs-landing
Removing `COMMIT_HASH` since including the commit hash was causing build issues with snooty parser v0.13.6.
> Remove COMMIT_HASH from docs-landing Makefile

- makefiles/Makefile.docs
- makefiles/Makefile.docs-atlas-cli
- makefiles/Makefile.docs-bi-connector
- makefiles/Makefile.docs-compass
- makefiles/Makefile.docs-datalake
- makefiles/Makefile.docs-landing
- makefiles/Makefile.docs-mongocli
- makefiles/Makefile.docs-mongodb-internal
- makefiles/Makefile.docs-php-library
- makefiles/Makefile.docs-stage
- makefiles/shared.mk
```
$ make -n -f ~/work/docs-worker-pool/makefiles/Makefile.docs  next-gen-html
if [ -n "" ]; then \
snooty build "/home/heli/work/snooty-parser" --output "/home/heli/work/snooty-parser/bundle.zip" --commit "607d8a9"  --rstspec=https://raw.githubusercontent.com/mongodb/snooty-parser/latest/snooty/rstspec.toml; \
if [ $? -eq 1 ]; then \
exit 1; \
else \
exit 0; \
fi \
else \
snooty build "/home/heli/work/snooty-parser" --output "/home/heli/work/snooty-parser/bundle.zip" --rstspec=https://raw.githubusercontent.com/mongodb/snooty-parser/latest/snooty/rstspec.toml; \
if [ $? -eq 1 ]; then \
exit 1; \
else \
exit 0; \
fi \
fi
rsync -az --exclude '.git' "/home/heli/work/snooty-parser/../../snooty" "/home/heli/work/snooty-parser"
cp /home/heli/work/snooty-parser/.env.production …
```
> DOP-2965: Switch all makefiles to using bundles

- api/controllers/v1/jobs.ts
- infrastructure/ecs-main/buckets.yml
This PR updates the s3 bucker polices to allow the archive job to recursively copy files. In previous tests where we archive sites under the primary docs bucket, the job would succeed since the bucker policy allows `s3:ListBucket` to the public. The  other buckets like `atlas` don't have the same policy statement.
After talking with @casthewiz we also decided that it's ok to skip the archive process for `docs-landing` since the build for that site is relatively fast. `docs-landing` is hard to archive with our current s3 layout, since other sites end up nested under the same folder. For example if we archive `/docs` we also include `/docs/realm`.
> [DOP-2715] bucket polices and job filter

- infrastructure/ecs-main/buckets.yml
- infrastructure/ecs-main/serverless.yml
I *think* these things are managed by the mysterious serverless framework now, and want to ensure our buckets end up with the correct policy, so updating here accordingly.
> DOP-3188: add bucket definitons for csharp to severless defs

- infrastructure/ecs-main/serverless.yml
Based on cursory investigation, Gatsby seems to make good use of additional CPUs and doesn't appear to be memory-bound. Testing out increasing the number of available CPUs on `prd` to assess its impact.
> Increase CPU units for prd instance

- makefiles/Makefile.cloud-docs
- makefiles/Makefile.cloud-docs-osb
- makefiles/Makefile.cloudgov-docs
- makefiles/Makefile.docs
- makefiles/Makefile.docs-atlas-cli
- makefiles/Makefile.docs-k8s-operator
- makefiles/Makefile.docs-landing
- makefiles/Makefile.docs-meta
- makefiles/Makefile.docs-mongocli
- makefiles/Makefile.docs-mongodb-vscode
- makefiles/Makefile.docs-node
- makefiles/Makefile.docs-php-library
- makefiles/Makefile.docs-stage
- makefiles/Makefile.mms-docs
- makefiles/Makefile.realm-docs-sdk-java
- makefiles/shared.mk
As of earlier this year, search manifest generation is handled by manifest build jobs rather than as a step in the Makefile. This has proven efficient and effective and stable, so we should remove this extraneous build step. Moreover, continued support of this build stage (which serves no purpose) is blocking progress on updating `mut` for manifest jobs.
The analogous changes have [already happened in cloud-docs-osb for testing purposes](https://github.com/mongodb/docs-worker-pool/commit/541ab6e810467a6cda2e772a1b7f0121a537f999), which behaved as expected ([staging link](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=63596a79dafcf7c33d890275)). 
Given that Makefile changes are scary, though, extra attention to review detail would be …
> DOP-3338: remove old search manifest generation step from Makefiles

- makefiles/shared.mk
[DOP-3413](https://jira.mongodb.org/browse/DOP-3413)
* Adds new command to make the OAS Page Builder module callable
* This should be safe to keep since it will be uncalled at the moment. If we don't end up moving forward with the module implementation, this can be easily reverted
* `OAS_MODULE_PATH` and `REDOC_PATH` aren't declared in the Makefile atm. Going to look into adding/declaring them as part of the `Dockerfile` setup for the module and Redoc fork
* `make oas-page-build` is to be called as a build command by the autobuilder after `next-gen-html` for [staging jobs](https://github.com/mongodb/docs-worker-pool/blob/42bd36b1f52e49c646a79474c12d299f33d774cb/src/job/stagingJobHandler.ts#L57) and [production jobs](https://github.com/mongodb/docs-worker-pool/blob/1a482242fa6f1463abb059884 …
> DOP-3413: Add command for OAS Page Builder module

- makefiles/shared.mk
Brings `oas-page-build` outside of the if statement checking for `PUSHLESS_DEPLOY_SHARED_DISABLED`. I totally forgot that I would need to add this to specific Makefiles with custom build targets. 
This change keeps the build target generalized and calls the OAS Page Builder module with every docs build. If the docs repo being built does not have any OpenAPI pages, then the module exits early, meaning it should be safe to have and call. If we need more specific instances of this target, we should look into re-adding within the if statement
> Generalize oas-page-build target

- .github/workflows/test.yml
https://github.com/mongodb/docs-worker-pool/actions/runs/3950988080/jobs/6764259757
see above action run.
no changes to detected, but `false` string is being evaluated as truthy.
> check for true string for dorny paths filter

- modules/persistence/src/services/assets/index.ts
- Persistence module was storing `/assets/<entryname>` from manifest zipfile in `documents` collection instead of designated `assets` collection. thanks @rayangler for the catch!
> Quick fix: point asset service to asset collection

- makefiles/Makefile.docs
- makefiles/Makefile.docs-atlas-cli
- makefiles/Makefile.docs-landing
- makefiles/Makefile.docs-mongocli
- makefiles/Makefile.docs-mongodb-internal
- makefiles/Makefile.docs-mongodb-internal-base
- makefiles/Makefile.docs-mongoid
- makefiles/Makefile.docs-php-library
- makefiles/Makefile.docs-ruby
- makefiles/Makefile.docs-stage
- makefiles/shared.mk
Invoke persistence module [installed via Docker images](https://github.com/mongodb/docs-worker-pool/pull/737) as a step after parser.
See test build logs in above PR.
[Errors are ignored and build steps continue after non terminal error from persistence module](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=63c1bc44c5cd20791001d2ec)
> DOP-3377: update makefiles to invoke persistence module

- infrastructure/ecs-main/serverless.yml
[DOP-3462](https://jira.mongodb.org/browse/DOP-3462)
This is a follow-on to [this ticket's original PR](https://github.com/mongodb/docs-worker-pool/pull/744). 
There was one more spot that the variables were referenced.
> DOP-3462-B: Cleanup env vars in serverless.yml

- .github/workflows/deploy-dev-ecs.yml
- .github/workflows/deploy-prd-ecs.yml
- .github/workflows/deploy-stg-ecs.yml
**Goal:** 
- update concurrency groups so that dev/stg/prd workflows can run in parallel
- remove dev deploy (unsure of purpose...) <- should we remove this completely? it hasn't been required ever, or successful in 4 months...
> update concurrency and remove deploy dev on push

- infrastructure/ecs-main/buckets.yml
[DOP-3404](https://jira.mongodb.org/browse/DOP-3404)
_Aside_: I weep as I open this pull request.
I researched and tried to find a way to use regex or wildcards for these, but those [don't seem to be possible](https://stackoverflow.com/questions/70304661/serverless-framework-how-to-use-wildcard-in-prefix-path) in the CloudFormation template. The only acceptable values for the [KeyPrefixEquals property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-websiteconfiguration-routingrules-routingrulecondition.html) are pure strings. 
It _might_ be worth trying to use a wildcard to see if it would work (`v1.1.*/`) because I have not found a definitive answer for this exact context, but if so, I'd like to try it only on `dotcomstg`.
**Note for future**: we are …
> DOP-3404: Redirects for atlas cli v1.1*, v1.2*, and 1.3*

- modules/persistence/src/services/metadata/ToC/index.ts
- modules/persistence/src/services/metadata/index.ts
- modules/persistence/tests/metadata/__snapshots__/ToC.test.ts.snap
**Goal:** 
1. when merging ToC nodes, we were previously including the root node of the associated product, which lead to a double nested ToC. **this PR unnests the children of the root node so that the associated product's root node's children are directly injected into the umbrella project's target node** 
2. given an associated product's root ToC can lead to two links (ie. https://www.mongodb.com/docs/atlas/cli/v1.3/ vs https://www.mongodb.com/docs/atlas/cli/stable), we need to be able to change the href of the ToC on the front end. **this PR adds an option to a ToC node. if it has node.options.versions: str[], it also has node.options.urls: {branchName: urlString}**
**Note:** 
Due to lack of clean up, ToC nodes front end ToC node's priorities will have to be updated so that a node's …
> DOP-3480: unnest merged ToC children, and add node.options.urls

- Dockerfile
* `apt install unzip` so we can extract the needful
* Remove the `FLIT_ROOT_INSTALL` environment variable, since we're no longer invoking `flit`
* Move the parser install logic to before the user is switched, so that we can install the parser to `/opt/snooty/`
* Add `/opt/snooty` to the system PATH so that `/opt/snooty/snooty` can be resolved
* Instead of git cloning and flit installing and all that jazz, just curl the salient parser release for linux x86_64, and unzip it in `/opt/`
Building the image succeeds, and confirmed `/opt/snooty/snooty` is accessible in the PATH.
Staged the server manual:
* https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=63d41e68cbd7d810f293c565
* https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/stable/
> DOP-3384: Use snooty parser binary builds

- Dockerfile
[DOP-3460](https://jira.mongodb.org/browse/DOP-3460)
* Updates the version tag format and version for the Redoc CLI.
* Tested locally, resulting in successful clone of new tag and successful local build with the Redoc CLI component.
> DOP-3460: Update tag version used for redoc-cli

- modules/persistence/tests/data/metadata.json
- package.json
`prettier` would catch unformatted files nested in the `modules/` directory, leading to potential errors in the GH Actions when running `npm run format` on the repo. 
This PR does the following:
* Uses `prettier` to format unformatted metadata json file in the persistence module. (Perhaps unnecessary given the bullet point below.)
* Ignores files nested in the `modules/` directory when formatting. This is consistent with the behavior for the root `.eslintrc.js` file.
> Ignore modules when formatting

- .github/workflows/deploy-stg-ecs.yml
- modules/persistence/src/services/metadata/ToC/index.ts
- modules/persistence/tests/metadata/ToC.test.ts
Enables the persistence module to merge ToC's and replace candidate insertion nodes even if that node has children.
Necessary for launch to accommodate a case for `atlas-cli`, and potentially necessary regardless. 
Ridealong to make BFS and candidate matching `Set` driven instead of doing list matching.
> Enable ToC merging into nodes with children

- api/controllers/v1/jobs.ts
[DOP-3524](https://jira.mongodb.org/browse/DOP-3503)
This PR simply adds the github commit hash to the successfully completed job's slack message for writer deploys.
> DOP-3524: Add commit hash to slack message

- modules/oas-page-builder/index.ts
- modules/oas-page-builder/src/services/database.ts
No ticket.
Added teardown functionality to close DB connection at end of oas-page-builder module processes.
> Close DB connection - oas-page-builder module

- makefiles/Makefile.docs
We added these curls to the internal server docs Makefile in PR #782. This PR adds them to the public server docs Makefile.
> DOCSP-28810: Add c++ and ruby driver examples to docs makefile

- .github/workflows/deploy-stg-ecs.yml
- Dockerfile
[DOP-3613](https://jira.mongodb.org/browse/DOP-3613)
* Moves the build step for `redoc-cli` as a release step in the redoc repo. The Dockerfile no longer needs to be responsible for building `redoc-cli`.
* Also updates the version of Redoc to include latest changes. These changes revolve around API versions and should not be expected to affect what's currently in production.
* Confirmed that test deploys are successful and OpenAPI pages are built. See build logs:
* [cloud-docs](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=642dafca9bdad5e7f48c1100)
* [atlas-app-services](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=642dafca9bdad5e7f48c1102)
> DOP-3613: Skip build step for redoc-cli

- makefiles/Makefile.docs-kotlin
Reminder that the get-build-dependencies step exists only so an autobuilder test passes, so I didn't bother to update the value. Hopefully we'll finish that ticket and get rid of those soon :)
> DOP-3647: add makefile for Kotlin driver

- src/services/repo.ts
By default, we assuming a repo is private if it's in the 10gen organization. This has largely worked, but isn't infallible, and mongodb/docs-kotlin is currently "internal", which is to say private outside of MongoDB but public within. Regardless, our colleagues need to be able to build it.
Having tested in integration, repos that are public and which do *not* have docs-builder-bot as a collaborator (e.g. mongodb/docs-compass) deploy correctly so this should do the needful.
As a follow-up we should figure out where "private" is used and whether we even need to keep that field. (I'll create a ticket).
> Use docs-builder-bot credentials for all git clone operations

- Dockerfile.legacy
```
$ hadolint-Linux-x86_64 ./Dockerfile.legacy 
./Dockerfile.legacy:9 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
./Dockerfile.legacy:38 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
./Dockerfile.legacy:39 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
```
I think these warnings are okay
> DOP-3592: Add legacy dockerfile

- modules/oas-page-builder/src/services/pageBuilder.ts
DOP-3659
During docs site builds, there are not uncommon times when a new gitHash for a new OpenAPI spec has been released however the spec itself (referenced through the gitHash) is not yet fully available. 
In these instances, our build logs correctly show us the error and the eventual successful build using a previous spec. However the logs show this in a confusing order and a large error log is worrying for the docs writers. Although the builds occur correctly, this logging should be more clear as to the fact that all is well.
Example of old confusing log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=643d73c15f7a7fd95617d611
> DOP-3659: Adjust OpenAPI build logs

- modules/persistence/tests/metadata/ToC.test.ts
- modules/persistence/tests/metadata/associated_products.test.ts
- modules/persistence/tests/metadata/metadata.test.ts
- modules/persistence/tests/utils.ts
PR creates a separate database for each suite, so it mitigates errors of duplicate keys as seen before.
This was caused by jest *randomly* choosing to either run the test suites sequentially or in a bunch, observed by myself and @rayangler unless we specified the option [--runInBand](https://jestjs.io/docs/29.3/cli#--runinband) which would be sequential.
Each caller should be generated a new db name, and thus no collision on Duplicate Error key
> DOP-3634: add test util to make new db for each test suite

- modules/persistence/src/services/assets/index.ts
- modules/persistence/src/services/connector/index.ts
- modules/persistence/src/services/metadata/repos_branches/index.ts
- modules/persistence/tests/services/connector.test.ts
DOP-3633
* Replaces `upsert` function to be `bulkUpsert`. Core logic upserts entire document object by ID, similar to previous `upsert` logic. Biggest difference is that `bulkWrite` is utilized instead of individual `updateOne` operations.
* Observations from local runs that might be interesting to see in production: 
* Connection count per build seems to be reduced with this change (observed from [cluster monitoring](https://cloud.mongodb.com/v2/5bad1d3d96e82129f16c5df3#/host/replicaSet/5d40b1bccf09a2026cbad969) based on timing with local builds). From console logs, I noticed that there'd be multiple attempts for the db client to connect with the previous iteration (probably through race conditions from promises).
* Bulk write implementation seems to save about 30 seconds for the server …
> DOP-3633: Use bulkWrites for asset upsertion

- makefiles/shared.mk
Companion PR to [3710 PR](https://github.com/mongodb/docs-worker-pool/pull/822).
This utilizes the data passed through to replace MUT_PREFIX with correct staging link when MUT_PREFIX is not available.
In writers staging, this was unavailable at this point in the build. 
We have recreated the correct path which is as follows: Project/User/GitBranchName
> Api version meta

- src/job/jobManager.ts
Noticed an issue with docs-k8s while trying to investigate a separate issue involving 200 responses but no slack message.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=648b398f67a273b816827da1
^^ Example job log of failure for docs-k8s-operator.
Performing mitigation in the same vein as mms-docs.
> [fix] Add docs-k8s-operator to exclusion array

- api/controllers/v1/github.ts
- api/controllers/v1/slack.ts
- api/controllers/v2/github.ts
- api/controllers/v2/slack.ts
- src/entities/job.ts
- tests/data/fullDoc.ts
- tests/data/fullDocWrongUrl.ts
DOP-3665
* Removes `private` field from job payload object. I couldn't find anywhere that actually used this field.
* Leaving some of the GH actions warnings as-is for now as the issues are pre-existing and aren't necessarily related to the `private` field. (I also wanted to avoid breaking anything that didn't need to change)
> DOP-3665: Remove private field from payload

- .github/workflows/deploy-stg-ecs.yml
- api/controllers/v1/jobs.ts
Adds explicit `client.close()` statements to the jobHandler to mitigate potential thread overuse from dangling connections.
Successful deploy log here:
https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=dotcom_queue&jobId=6494b9aa0379b4804917fa5e
> Add explicit client closure to V1 Lambdas

- modules/persistence/src/services/metadata/associated_products/index.ts
Fixes a case where associating properties with null `urlAliases` causes a terminal error within ToC merging.
Apparently default assign of the `[]` in the destructure on the line prior to my change (`119`) does not overwrite explicit `null`, only undefined 🤔 
Without handling, error manifests as:
```
Error at time of merging associated ToC entries: TypeError: Cannot read property '0' of null
Error during umbrella metadata update: TypeError: Cannot read property '0' of null
Persistence Module encountered a terminal error: TypeError: Cannot read property '0' of null
/Users/cassidy.schaufele/Documents/GitHub/docs-worker-pool/modules/persistence/dist/src/services/metadata/associated_products/index.js:75
const alias = urlSlug || urlAliases[0] || (publishOriginalBranchName && gitBranchName);
``` …
> [DOP-3755] Fix potential null access terminal error case

- makefiles/Makefile.docs-ecosystem
Merge in tandem with the docs-ecosystem PR that adds the images (https://github.com/mongodb/docs-ecosystem/pull/897)
> DOP-3832: remove dependency on docs-assets

- makefiles/shared.mk
This appears to be the only place we still assume the base branch is `master`! We'll very happily let people stage branches called `master` now (e.g. https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=queue&jobId=64bfc8c287b3b36046c9bed3 builds a cloud-docs branch named `master`, which we used to -- some many moons ago -- just auto-fail) and there is no other docs-worker-pool code I could find that cared.
Custom deploys are only defined for docs-mongodb-internal, which has no deploy support being internal-only, so the other Makefiles didn't need touching.
> DOP-3837: remove base branch==master assumption

- src/repositories/updatedDocsRepository.ts
* Updates the `updated_at` field when marking ASTs for deletion. This is needed so that the API and source plugin can see these newly marked pages as "updated".
* The metadata document should not need this same field because the latest metadata document is returned regardless of if the timestamp has changed.
> Add updated time when marking data for deletion

- cdk-infra/lib/constructs/api/webhook-env-construct.ts
This is a quick fix so that the slackbot provides the correct `Env` value in the build completion message.
> [HOTFIX]: Add STAGE environment variable to webhooks

- makefiles/Makefile.docs-landing
Noticed this weird error when trying to build `docs-landing` ([build log](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=queue&jobId=64cd559867dbe91010006af0)):
```
Error: Command failed: make next-gen-html GH_USER=rayangler
INFO:snooty.main:Snooty 0.14.3 starting
INFO:snooty.parser:cache: 0 hits and 8 misses
/bin/sh: 6: Syntax error: "if" unexpected
make: *** [Makefile:53: next-gen-html] Error 2
```
I was able to reproduce this issue locally using a minimal example, so I believe this change should fix it! 🤞
> Remove extra if in docs-landing Makefile

- .github/workflows/deploy-stg-ecs.yml
- api/handlers/github.ts
- src/job/stagingJobHandler.ts
- src/repositories/metadataRepository.ts
- src/repositories/updatedDocsRepository.ts
- tests/unit/api/github.test.ts
DOP-3907
* Adds new `updated_at` field to metadata documents when they are being marked for deletion. This will be leveraged by the Snooty Data API to allow it to identify that there was a change in the metadata for a project + branch without needing to perform a new parse.
* Fixes a small bug with checking the feature flag for the preview webhook. It was checking for a truthy string, which would be truthy even if the env's value was "false". Not a big deal, but this has resulted in unintentional calls to one of the Gatsby Cloud sites.
> DOP-3907: Update time for marking metadata doc deletion

- src/repositories/jobRepository.ts
- tests/unit/repositories/jobRepository.test.ts
`findOneAndUpdate` apparently returns the original document nested in a response object. This PR hopes to fix this by returning the actual value.
> Return the value of the update

- .github/workflows/deploy-prd-enhanced-webhooks.yml
- .github/workflows/deploy-stg-enhanced-webhooks.yml
- cdk-infra/lib/constructs/queue/queues-construct.ts
I increased the `visibilityTimeout` property for the queues because there was the following error occurred when attempting to deploy the staging environment:
```
auto-builder-stack-enhancedApp-dotcomstg-webhooks | 9:28:34 PM | CREATE_FAILED        | AWS::Lambda::EventSourceMapping | api/handleJobsLambda/SqsEventSource:autobuilderstackenhancedAppdotcomstgqueuesJobUpdatesQueue862D290D (apihandleJobsLambdaSqsEventSourceautobuilderstackenhancedAppdotcomstgqueuesJobUpdatesQueue862D290D35BB8AD7) Resource handler returned message: "Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 120 seconds (Service: Lambda, Status Code: 400, Request ID: 14ed7a5c-9f22-4c81-948a-35ae2e028b63)" (RequestToken: cabb6d1e-271d-ac18-479d-157538643662, HandlerErrorCode: …
```
> add ci command for webhooks and increase visibility timeout

- .github/workflows/deploy-stg-ecs.yml
- api/handlers/github.ts
- src/repositories/metadataRepository.ts
- src/repositories/updatedDocsRepository.ts
- tests/unit/api/github.test.ts
DOP-3943
* Fixes a potential future bug where if 2 users have the data with the same project + branch, the deletion webhook could mark every data with that project + branch for deletion instead of only the user's fork of the data.
> DOP-3943: Mark data for deletion based on user

- modules/persistence/index.ts
- modules/persistence/src/services/connector/pool/index.ts
DOP-3801
The Persistence Module already had functionality implemented to cache db connections, but the asynchronous nature of the Promise.all call was not allowing time for the first connection to succeed before each function in turn needed it. This led to four connections rather than the desired one to be shared.
Both db connections needed for the module are now awaited, created, and cached before the module moves on.
> DOP-3801: Ensure db pools/topologies are used efficiently

- makefiles/shared.mk
DOP-3951
* This PR splits the persistence module apart from the `next-gen-html` rule. This is an additional Makefile change needed to allow the Gatsby Cloud preview webhook to be called immediately after the persistence module is called.
* The individual Makefiles that have their own calls to `next-gen-html` have been unchanged to avoid breaking persistence module behavior immediately (since updates to repo-specific Makefiles are immediately available in prod). This does mean that the persistence module may be called twice in a row for certain repos for a short moment of time in prod. Removing the duplicate persistence module calls should be removed from repo-specific Makefiles as a fast-follow after https://github.com/mongodb/docs-worker-pool/pull/889 is released on prod.
> DOP-3951: Separate persistence module Makefile rule

- api/controllers/v2/jobs.ts
- cdk-infra/lib/constructs/api/webhook-api-construct.ts
DOP-3968
* Adds existing v1 webhooks for Gatsby Cloud builds to the enhanced Autobuilder. The logic should be the same for v1 and v2 as they are fully exported from their respective `api/handlers/*.ts` files.
* Envs needed for such webhooks should have already been added in previous PRs, but please let me know if I missed something! Notably, the envs include the following and can be found defined in [default.json](https://github.com/mongodb/docs-worker-pool/blob/ac389132d575eeb8f0035db7d6330f974f611fd8/cdk-infra/static/api/config/default.json), [custom-environment-variables.json](https://github.com/mongodb/docs-worker-pool/blob/ac389132d575eeb8f0035db7d6330f974f611fd8/cdk-infra/static/api/config/custom-environment-variables.json), and …
> Add Gatsby Cloud-related webhooks to Enhanced Autobuilder

- src/enhanced/job/enhancedJobHandlerFactory.ts
Fixes an issue where the `repoEntitlements` field wasn't being passed down to the enhanced autobuilder job handler.
> Add entitlements repo to enhanced autobuilder

- cdk-infra/lib/constructs/api/webhook-env-construct.ts
This PR adds the `REPO_BRANCHES_COL_NAME` env value from Parameter Store to the Webhook/API construct. Seems like this was already added to the Worker construct, so I just followed what was already there.
See `payload.project` in this [build log](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e9160a24fcc731b48f77ef) for updated payload change.
> Add missing repo branches collection name

- .github/workflows/deploy-stg-ecs.yml
- modules/oas-page-builder/src/services/pageBuilder.ts
- modules/oas-page-builder/tests/unit/services/pageBuilder.test.ts
DOP-3963 has most details, but TLDR: 
We want to render only the latest spec at the base route of any versioned OpenAPI spec - this resolves some out-of-order issues with resources in dropdowns vs version in the left sidenav, and consumers of the spec typically want to see the latest versions regardless.
https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/master/reference/api-resources-spec/v2/
> DOP-3963: Render only latest version of spec at base spec component

- api/controllers/v1/jobs.ts
- api/controllers/v2/jobs.ts
Adds blurb to encourage writers to update to the new webhook. I am very open to copy enhancement suggestions.
Message for build on non-enhanced stg webhook:
Message for build on enhanced stg webhook:
Message for /test-deploy:
> DOP-3977: encourage writers to switch webhooks 🥕

- cdk-infra/lib/constructs/api/webhook-env-construct.ts
When attempting to deploy another feature branch stack, I ran into an error stating that I had a duplicate parameter store value when deploying my change. This is due to the fact that I added code to create a new parameter store value in the CDK. 
[Failed job for reference](https://github.com/mongodb/docs-worker-pool/actions/runs/6192385254/job/16812369888)
```sh
Failed resources:
auto-builder-stack-enhancedApp-stg-docker-buildspeed-poc-webhooks | 12:49:16 AM | CREATE_FAILED        | AWS::SSM::Parameter             | ssmVars/monorepoPathFeature (ssmVarsmonorepoPathFeature488111CB) /env/stg/docs/worker_pool/monorepo/path_feature already exists in stack arn:aws:cloudformation:us-east-2:***:stack/auto-builder-stack-enhancedApp-stg-webhooks/c7b84a20-3865-11ee-9bbf-0a716bdfa1cb**
```
To …
> [BUGFIX]: Fix duplicate parameter deploy error 

- makefiles/Makefile.docs-ruby
The ruby docs should include a tutorial whose docs live in the mongodb/bson-ruby repository. We've added the bson-ruby submodule to the source; this will rsync the relevant file into the relevant directory. Tested locally with satisfactory outcome.
> DOP-4013: add bson-ruby submodule for tutorial

- .gitignore
- makefiles/shared.mk
DOP-3723
* Passes down an Autobuilder job ID to the persistence module.
* Related Autobuilder change can be found at #913.
> DOP-3723: Pass Autobuilder job ID to persistence module

- .github/workflows/deploy-feature-branch.yml
Addresses the issue @mmeigs ran into [here](https://github.com/mongodb/docs-worker-pool/pull/909#issuecomment-1730132719). Deploying the queues should never cause an issue, but if we deploy everything at the same time, we won't subsequently re-run the deploy for the queues. This way, if the worker or webhooks fail, the queues will still be created.
> Break up deploy for feature branch

- modules/persistence/src/services/connector/index.ts
DOP-4096
* This should hopefully prevent (or at least minimize) the issue we've been seeing with missing metadata during Gatsby Cloud builds. The idea is that the `created_at` timestamp would be skewed due to using the Autobuilder job ID's timestamp, leading to fetches from the Gatsby preview source plugin and Snooty Data API skipping over data during parallel builds. The ticket has more context, along with the associated frontend PR that handles generating warnings for this event
> DOP-4096: Create new timestamp when inserting pages and metadata

- Dockerfile
- Dockerfile.enhanced
- src/job/jobHandler.ts
- tests/unit/job/productionJobHandler.test.ts
Work on previous PR depended on changes to the meta branch that were present in `monorepo-pub-branches`. This PR resets all of these references back to the correct `meta` branch.
> Change ref back to `meta`

- makefiles/Makefile.cloud-docs
- makefiles/Makefile.docs-landing
- makefiles/shared.mk
- publishedbranches/docs-monorepo/cloud-docs.yaml
- publishedbranches/docs-monorepo/docs-landing.yaml
DOP-4079
As a follow-up to [PR 929](https://github.com/mongodb/docs-worker-pool/pull/929), this alteration to the `meta` branch is necessary for successful monorepo `Job` builds. 
Both changes have to do with the now-double-layered monorepo paradigm (ie. `docs-monorepo/cloud-docs` vs `cloud-docs`).
1. The new PATH_TO_SNOOTY correctly points to the directory level where Snooty is installed. 
2. New publishedBranches files to account for the nested level of all requests. In the future, would love to not have duplicates such as these, but with our Makefiles being removed soon - it could just be a small necessary evil for now
> DOP-4079 follow-up - ensure monorepo jobs access correct Makefiles

- config/custom-environment-variables.json
- infrastructure/ecs-main/serverless.yml
- src/job/jobHandler.ts
- tests/utils/jobHandlerTestHelper.ts
Follow up to [previous PR](https://github.com/mongodb/docs-worker-pool/pull/942)
Above PR is causing [staging build errors](https://github.com/mongodb/docs-worker-pool/actions/runs/7009848133/job/19069167991) due to [env variable names differing](https://github.com/mongodb/docs-worker-pool/pull/937/files#diff-822cad868abefc13eb54d59cc2aedb564b3dd0fab6ca48047e2dbbb13ddb2875R28) (fix is [here](https://github.com/mongodb/docs-worker-pool/pull/943/files#diff-822cad868abefc13eb54d59cc2aedb564b3dd0fab6ca48047e2dbbb13ddb2875L28))
> DOP-3998: use same name for env vars

- config/default.json
- infrastructure/ecs-main/ecs_service.yml
Attempt #2 at using same var names (casing, oof)
Looking into why [this PR](https://github.com/mongodb/docs-worker-pool/pull/943/) did not fail on build for feature branch, but stage build failed
Edit: due to fact we are using CDK deploy for feature branch vs SLS deploy in stage
> DOP-3998: casing variables

- src/services/containerServices.ts
Just saw this error in Cloudwatch. Honestly not sure if this was from what I'm dealing with, but I found this in the code and thought it might be worth adding to make sure this kind of error doesn't occur. 
Error seen in Cloudwatch:
```{
"errorType": "TypeError",
"errorMessage": "Cannot read properties of undefined (reading 'lastStatus')",
"stack": [
"TypeError: Cannot read properties of undefined (reading 'lastStatus')",
"    at ECSContainer.stopZombieECSTask (/var/task/api/controllers/v1/jobs.js:78232:25)",
"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
"    at async stopECSTask (/var/task/api/controllers/v1/jobs.js:78815:3)",
"    at async /var/task/api/controllers/v1/jobs.js:78761:15",
"    at async Promise.all (index 0)",
"    at async …
```
> Bugfix: Optional chaining to shortcircuit error with container

- makefiles/Makefile.docs
- makefiles/Makefile.docs-mongodb-internal
Go Driver team changed the location of their examples, which broke our builds. This PR updates the location of the file we curl for the internal and public server docs.
> Change location for Go examples for server docs makefile

- .gitignore
- makefiles/Makefile.docs-laravel
DOP-4192
* Made a barebones Makefile for the new `docs-laravel` repo. I don't believe this has any crazy build steps, so I kept it as minimal as possible.
* (Bonus) Added `dist/` to the `.gitignore` file to allow for a seamless transition between local Autobuilder usage and `meta` branch updates. Otherwise, `dist/` might appear and can accidentally be added to the commit.
> DOP-4192: Add Makefile for docs-laravel

- makefiles/Makefile.docs-laravel
DOP-4237
* Introduces a build step to fetch git submodule for `docs-laravel`.
* Copied over logic from other Makefiles that have custom build steps to ensure that the submodule can be fetched.
* [Example build log](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=queue&jobId=659f2488914de3d7f7644a95) - This build fails as expected due to the git submodule currently having no content for Snooty to parse.
> DOP-4237: Fetch submodules for docs-laravel

- .github/workflows/README.md
- .github/workflows/clean-feature-branch.yml
- .github/workflows/deploy-feature-branch.yml
- .github/workflows/update-feature-branch.yml
Recently, changes have been made to improve the `Update Feature Branch Infrastructure` workflow deployment speed. There was a bug though that leads to new pull requests to fail to upload their feature branch resources.
Functionality has also been added to delete the GitHub Actions cache for each feature branch.
> [HOTFIX]: Add correct cache commands

- makefiles/Makefile.docs-pymongo
Annoyingly my tab was not good enough! Also deleted an unused line break.
Error in log:
`reason: "Error: Command failed: make get-build-dependencies
Makefile:21: *** missing separator.  Stop.`
> bug. Fix Makefile separator

- .github/workflows/deploy-prd-enhanced-cache.yml
Realized I copied and pasted the name of the webhook release workflow and used it for the cache updater, oops!
> Update name of cache update workflow

- src/job/jobHandler.ts
Accidentally added downloading/getting build dependencies when building **with** Makefiles. This PR removes it.
[Build log building docs project](https://workerpoolstaging-qgeyp.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d637137111165982e1be7d)
> Removing lines for downloadBuildDependencies when building with makefiles

- .github/workflows/deploy-stg-ecs.yml
[DOP-4306](https://jira.mongodb.org/browse/DOP-4306)
Accidentally left DOP-4306 in `deploy-stg-ecs.yml` in a previous PR! This removes it!
> DOP-4306-b remove branch from preprd

- cdk-infra/utils/ssm.ts
- src/enhanced/utils/filter-sensitive-values.ts
- src/enhanced/utils/get-sensitive-values.ts
- src/services/logger.ts
- tests/unit/services/hybridJobLogger.test.ts
DOP-4240
**Context**: The code changes provided add a filtering method that looks for sensitive values from our param store, and redacts any sensitive values found in the message that is being logged.
> :sparkles: DOP-4240 implements filtering sensitive values method to prevent sensitive values being logged

- makefiles/Makefile.docs-languages
DOP-4359
This adds a Makefile for the new repo: [docs-languages](https://github.com/mongodb/docs-languages)
This will hold the general Language landing page and all the specific language landing pages
> DOP-4359: docs-languages Makefile

- cdk-infra/utils/buckets.ts
- infrastructure/ecs-main/buckets.yml
- infrastructure/ecs-main/serverless.yml
DOP-4359
This adds the necessary S3 Buckets for `docs-languages`
It also removes the intgr buckets that don't even exist in S3...?
> DOP-4359: add LanguagesBucket for s3

- makefiles/Makefile.docs
- makefiles/Makefile.docs-atlas-cli
- makefiles/Makefile.docs-atlas-operator
- makefiles/Makefile.docs-landing
- makefiles/Makefile.docs-laravel
- makefiles/Makefile.docs-mongocli
- makefiles/Makefile.docs-mongodb-internal
- makefiles/Makefile.docs-mongodb-internal-base
- makefiles/Makefile.docs-mongoid
- makefiles/Makefile.docs-php-library
- makefiles/Makefile.docs-ruby
We pass the `${NO_CACHING}` variable to snooty in shared.mk, but a lot of properties override this for some reason.
Ensure that it gets passed in so production builds do not use the cache.
> Ensure we pass ${NO_CACHING} properly

- .github/workflows/deploy-stg-ecs.yml
- src/services/slack.ts
This PR is a hotfix for an issue that prevents non-admin users from using the /deploy slack command to deploy repos following the release of [DOP-4481](https://jira.mongodb.org/browse/DOP-4481)
> DOP-4481 hotfix

- src/services/commandExecutor.ts
- tests/unit/services/shellCommandExecutor.test.ts
[DOP-4701](https://jira.mongodb.org/browse/DOP-4701)
The actual fix is the one line change in `commandExecutor.ts`.
The annoying part was making the test work:
* The existing test incorrectly mocked the `child_process.exec()` interface.
* According to the node docs, the exception raised by `util.promisify(child_process.exec())` will always have a `stdout` property. But just in case the exception get raised by something *else* in the try block, it'll fall back to returning `''` as in the current behavior.
* `util.promisify(child_process.exec)` has a custom promisifier (`child_process.exec[util.promisify.custom]`) that considerably changes the interface, but that jest loses when you call `jest.mock('child_process')`, and because of jest magic tomfoolery, I couldn't find any tidy way to …
> DOP-4701: Preserve stdout in ShellCommandExecutor

- cdk-infra/lib/constructs/worker/worker-env-construct.ts
- config/custom-environment-variables.json
- infrastructure/ecs-main/ecs_service.yml
- src/commands/src/helpers/dependency-helpers.ts
- src/job/jobHandler.ts
- tests/data/data.ts
- tests/utils/jobHandlerTestHelper.ts
DOP-4669
This PR adds logic to fetch AWS SM Param Store variables and use it to populate environment variables in the autobuilder + snooty front end
- These key/values have been added to the param store manually in S3, with `dotcomprd` and `prd` values being false as [described in ticket](https://jira.mongodb.org/browse/DOP-4669?focusedCommentId=6373200&focusedId=6373200&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6373200) 
- - [X] This PR does not introduce changes that should be reflected in the README
> DOP-4669: add env var for enabling dark mode

- cdk-infra/lib/constructs/worker/worker-env-construct.ts
- config/custom-environment-variables.json
- infrastructure/ecs-main/ecs_service.yml
- infrastructure/ecs-main/serverless.yml
- src/job/jobHandler.ts
- tests/data/data.ts
- tests/utils/jobHandlerTestHelper.ts
DOP-4602
* This adds a new feature flag to conditionally show specific locales in the frontend. The original intention was to have it specifically for Japanese, but I pre-emptively made it more generalized in case we need to reuse it for different languages.
> DOP-4602: Add feature flag to conditionally show WIP locales

- makefiles/Makefile.docs-ruby
This is an intermediate step to allow building docs-ruby without that submodule.
This line should go away entirely once the transition to not using a submodule is complete.
DOP-4704
> DOP-4704: Ignore errors when rsyncing mongo-ruby-driver

- infrastructure/ecs-main/buckets.yml
DOP-4725
**These changes have already been applied to the S3 console to address the 404ing links**
> DOP-4725: fix kuberentes links

- makefiles/Makefile.docs
- makefiles/Makefile.docs-atlas-cli
- makefiles/Makefile.docs-atlas-operator
- makefiles/Makefile.docs-landing
- makefiles/Makefile.docs-laravel
- makefiles/Makefile.docs-mongocli
- makefiles/Makefile.docs-mongodb-internal
- makefiles/Makefile.docs-mongodb-internal-base
- makefiles/Makefile.docs-mongoid
- makefiles/Makefile.docs-php-library
- makefiles/Makefile.docs-ruby
- makefiles/shared.mk
DOP-4758
- Makefiles should point at the env var ([specified in Dockerfile](https://github.com/mongodb/docs-worker-pool/pull/1057/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R25)) or fallback to the main branch for latest rstspec
- - [X] This PR does not introduce changes that should be reflected in the README
> DOP-4758: remove flag for rstspec

- makefiles/Makefile.docs-kotlin-sync
DOP-4776
Adds the new makefile for `kotlin-sync`
> :wrench: DOP-4776 adds the new makefile

- makefiles/Makefile.docs-mongoid
This is required for removing the submodule configuration from mongodb/docs-mongoid.
DOP-4809
> DOP-4809: Permit mongoid submodule setup to fail

- makefiles/Makefile.docs-php-library
> DOP-4884: Permit docs-php-library submodule setup to fail

- api/controllers/v2/jobs.ts
[DOP-4876](https://jira.mongodb.org/browse/DOP-4876)
Provides a deprecation notice for writers using the Autobuilder for staging builds (`prd`)
> [DOP-4876]: Add deprecation warning message to Autobuilder staging builds

- api/controllers/v1/github.ts
- api/controllers/v2/github.ts
This PR disables the Autobuilder for staging builds. I've changed the endpoint to return a 404 when a webhook POST request comes through.
> Disable Autobuilder for Writer's Staging

- infrastructure/ecs-main/buckets.yml
DOP-5065
- We have a maximum of 50 redirect rules. We are approaching this (47 at this bucket) and will need to resort to object redirects at 50.
- From [AWS docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-routingrulecondition.html), it looks like a trailing slash is preferred, but wondering why we don't have trailing slashes for redirect prefix rules. I've included them in the change, but can make this change bigger to the existing redirects. This has caused issues before (ie. [bad redirects from bi-connector versions](https://jira.mongodb.org/browse/DOP-5051))
Tested in staging env:
https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/compass/master
With [redirect rules](https://us-east-2.console.aws.amazon.com/s3/bucket/docs-mongo …
> DOP-5065: add redirect rule for compass - master

- infrastructure/ecs-main/buckets.yml
[DOP-5051](https://jira.mongodb.org/browse/DOP-5051)
The bucket-level redirect for bi-connector v2.1 is accidentally capturing paths for other versions, leading to bad redirects such as docs/bi-connector/v2.10-> docs/bi-connector/current0 and docs/bi-connector/v2.11-> docs/bi-connector/current11
This PR adds a trailing slash so that the redirect no longer captures paths for other versions on accident.
> Update V2.1 Bi-connector redirect

- modules/persistence/src/services/pages/index.ts
[DOP-5395](https://jira.mongodb.org/browse/DOP-5395)
Persistence Module not updating updated_documents collection
Hotfix so that persistence module updates and uploads all documents with 'docsworker-xlarge' as the parser user. Should be undone in DOP-5405
Example: { page_id:
"compass/docsworker-xlarge/master/query-with-natural-language" }
> DOP-5395: Persistence Module not updating updated_documents collection

- infrastructure/ecs-main/buckets.yml
DOP-5490
* Attempts to add trailing slashes to the redirects to avoid having examples like "v1.31" from being caught in redirects away from "v1.3".
* We'll test in preprd first and roll back as needed.
> DOP-5490: Add trailing slashes to redirects for kubernetes-operator
